import type { Metadata } from 'next'
import TheNavbar from './TheNavbar'
import { Kanit } from 'next/font/google'

const kanit = Kanit({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <TheNavbar />
      <div className={`flex min-h-screen flex-col items-center justify-between p-24 ${kanit.className} `}>
        {children}
      </div>
    </>
  )
}